#!/usr/bin/env python3
"""Generate ``docs/ENV_REFERENCE.md`` from the validated settings classes.

Schema-from-model, not hand-maintained prose: a hand-written env-var table
drifts from the actual `pydantic-settings` fields the moment someone adds or
renames one. This script instead walks `ServerSettings.model_fields` and
`ReloadSettings.model_fields` directly — the same two classes that are
already the single source of truth for what each service reads from the
environment (see the root `AGENTS.md` "one validated settings file per
deployable service" rule) — and emits one table per service.

Every field must carry a `Field(description=...)`; `_description` raises if
one is missing, so a new env var literally cannot ship undocumented.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from pydantic import SecretStr
from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings

from ssm_reload.config import ReloadSettings
from ssm_server.settings import ServerSettings

DEFAULT_OUTPUT = "docs/ENV_REFERENCE.md"

HEADER = """# Environment variable reference

<!-- Generated by scripts/generate_env_reference.py from ServerSettings and
     ReloadSettings. Do not hand-edit — regenerate with `make env-ref`. -->

Every environment variable each service honors, generated directly from its
`pydantic-settings` model: `ServerSettings` in
[`../ssm_server/settings.py`](../ssm_server/settings.py) and
`ReloadSettings` in [`../ssm_reload/config.py`](../ssm_reload/config.py).
Those two classes are already the single source of truth the code reads
from — this file just makes that truth readable without opening the
source."""

# `DOCKER_HOST` is a standard Docker SDK variable (`docker.from_env()`
# reads it directly) — it is not, and should never become, a
# `ReloadSettings` field, so it can't be discovered by walking
# `model_fields`. Hardcoded here, clearly marked, so the reference stays
# complete without inventing a fake settings field just to be generated.
DOCKER_HOST_ROW = (
    "| `DOCKER_HOST` | | local Docker socket | Standard Docker endpoint "
    "override, honored directly by the Docker SDK's `docker.from_env()` "
    "— not a `ReloadSettings` field; `ssm-reload` never reads or "
    "validates it itself. |"
)

TABLE_HEADER = (
    "| Variable | Required | Default | Description |",
    "| --- | --- | --- | --- |",
)


def _description(field_name: str, info: FieldInfo) -> str:
    if not info.description:
        raise ValueError(
            f"Field {field_name!r} on {info!r} has no "
            "Field(description=...) — add one before regenerating "
            f"{DEFAULT_OUTPUT}."
        )
    return info.description


def _variable(field_name: str, info: FieldInfo) -> str:
    alias = info.validation_alias
    if isinstance(alias, str):
        return f"`{alias}`"
    return f"`{field_name.upper()}`"


def _default(info: FieldInfo) -> str:
    if info.is_required():
        return "—"
    default = info.get_default(call_default_factory=True)
    if default is None:
        return "—"
    if isinstance(default, SecretStr):
        # Never echo a secret's actual default value, even if it is empty
        # today — a future non-empty default must not leak through docs.
        return "(empty)" if default.get_secret_value() == "" else "(hidden)"
    if isinstance(default, str):
        return "(empty)" if default == "" else f"`{default}`"
    if isinstance(default, float) and default.is_integer():
        return f"`{int(default)}`"
    return f"`{default}`"


def _rows(model: type[BaseSettings]) -> list[str]:
    rows = []
    for field_name, info in model.model_fields.items():
        required = "✅" if info.is_required() else ""
        rows.append(
            f"| {_variable(field_name, info)} | {required} | "
            f"{_default(info)} | {_description(field_name, info)} |"
        )
    return rows


def _table(
    title: str, model: type[BaseSettings], extra_rows: list[str] | None = None
) -> list[str]:
    lines = [f"## {title}", "", *TABLE_HEADER, *_rows(model)]
    if extra_rows:
        lines.extend(extra_rows)
    lines.append("")
    return lines


def build_reference() -> str:
    lines = [HEADER, ""]
    lines.extend(_table("ssm_server (`ServerSettings`)", ServerSettings))
    lines.extend(
        _table(
            "ssm_reload (`ReloadSettings`)",
            ReloadSettings,
            extra_rows=[DOCKER_HOST_ROW],
        )
    )
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the environment variable reference from "
            "ServerSettings and ReloadSettings."
        )
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help="Path to write the generated reference",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Fail if the output file is missing or out of date instead "
            "of (re)writing it"
        ),
    )
    args = parser.parse_args()

    output_path = Path(args.output)
    content = build_reference()

    if args.check:
        current = (
            output_path.read_text(encoding="utf-8")
            if output_path.exists()
            else None
        )
        if current != content:
            print(
                f"{output_path} is out of date with the settings "
                "classes; run `make env-ref` to regenerate."
            )
            return 1
        print(f"{output_path} is up to date")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Wrote environment variable reference to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
