name: Build and deploy multiarch image

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "docs/**"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image"
        required: true
        default: "latest"

jobs:
  docker:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version information
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION_FULL="${{ github.event.inputs.tag }}"
            # Remove 'v' prefix if present
            VERSION_FULL=${VERSION_FULL#v}
          elif [ "${{ github.event_name }}" = "release" ]; then
            VERSION_FULL="${{ github.event.release.tag_name }}"
            # Remove 'v' prefix if present
            VERSION_FULL=${VERSION_FULL#v}
          else
            # Extract from git tag
            VERSION_FULL=${GITHUB_REF#refs/tags/v}
          fi

          # Split version into parts
          IFS='.' read -r VERSION_MAJOR VERSION_MINOR VERSION_PATCH <<< "$VERSION_FULL"
          VERSION_SHORT="$VERSION_MAJOR.$VERSION_MINOR"

          echo "VERSION_FULL=$VERSION_FULL" >> $GITHUB_OUTPUT
          echo "VERSION_SHORT=$VERSION_SHORT" >> $GITHUB_OUTPUT
          echo "VERSION_MAJOR=$VERSION_MAJOR" >> $GITHUB_OUTPUT

          echo "Versions: Full=$VERSION_FULL, Short=$VERSION_SHORT, Major=$VERSION_MAJOR"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/bearlike/simple-secrets-manager:latest,ghcr.io/bearlike/simple-secrets-manager:${{ steps.version.outputs.VERSION_FULL }},ghcr.io/bearlike/simple-secrets-manager:${{ steps.version.outputs.VERSION_SHORT }},ghcr.io/bearlike/simple-secrets-manager:${{ steps.version.outputs.VERSION_MAJOR }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
